# Generated by Django 4.1.4 on 2023-01-31 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("produit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ajouteFavori", models.BooleanField(default=False)),
                ("dateFavori", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "produit",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produit.produit",
                        verbose_name="produit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.client",
                        verbose_name="client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commentaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Description", models.TextField()),
                ("dateCommentaire", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "produit",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produit.produit",
                        verbose_name="produit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.client",
                        verbose_name="client",
                    ),
                ),
            ],
        ),
    ]
