# Generated by Django 4.1.4 on 2023-01-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentaire",
            name="archiver",
            field=models.BooleanField(default=False),
        ),
    ]
