# Generated by Django 4.1.4 on 2023-01-31 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commande", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_facture", models.CharField(max_length=50)),
                ("tva", models.CharField(blank=True, max_length=150, null=True)),
                ("reduction", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "modalite_paiement",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("date_facture", models.CharField(max_length=50)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commander",
                        to="commande.commande",
                    ),
                ),
            ],
        ),
    ]
