# Generated by Django 4.1.4 on 2023-11-08 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produit", "0005_couleur_pointures_remove_produit_couleurs_and_more"),
        ("panier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="couleur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produit.couleur",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="pointure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produit.pointures",
            ),
        ),
    ]
