# Generated by Django 4.1.4 on 2023-12-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('panier', '0002_article_couleur_article_pointure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
