# Generated by Django 4.1.4 on 2023-01-31 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_categorie", models.CharField(max_length=255)),
                ("archiver", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SousCategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_sous_categorie", models.CharField(max_length=255)),
                ("quantite_sous_categorie", models.IntegerField(default=1)),
                ("archiver", models.BooleanField(default=False)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorie",
                        to="categorie.categorie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeCategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_type_categorie", models.CharField(max_length=255)),
                ("quantite_type_categorie", models.IntegerField(default=1)),
                ("archiver", models.BooleanField(default=False)),
                (
                    "sous_categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_categorie",
                        to="categorie.souscategorie",
                    ),
                ),
            ],
        ),
    ]
