# Generated by Django 4.1.4 on 2023-02-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categorie", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="typecategorie",
            name="sous_categorie",
        ),
    ]
