# Generated by Django 4.1.4 on 2023-02-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produit", "0003_remove_produit_type_categorie_produit_sous_categorie"),
        ("categorie", "0002_remove_typecategorie_sous_categorie"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TypeCategorie",
        ),
    ]
