# Generated by Django 4.1.4 on 2023-01-31 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categorie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_produit", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("lien_image", models.CharField(blank=True, max_length=255, null=True)),
                ("prix", models.FloatField(default=0)),
                ("taux_pourcentage", models.IntegerField(default=100)),
                ("disponible", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("solder", models.BooleanField(default=False)),
                ("archiver", models.BooleanField(default=False)),
                (
                    "type_categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_categorie",
                        to="categorie.typecategorie",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Produits",
                "ordering": ("-date_creation",),
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produit.produit",
                    ),
                ),
            ],
        ),
    ]
