# Generated by Django 4.1.4 on 2023-02-22 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categorie", "0003_delete_typecategorie"),
        ("produit", "0003_remove_produit_type_categorie_produit_sous_categorie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="lien_image",
        ),
        migrations.AddField(
            model_name="produit",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="categorie.categorie",
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="couleurs",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="produit",
            name="image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to=""
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="tailles",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produitImage",
                to="produit.produit",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="sous_categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="categorie.souscategorie",
            ),
        ),
        migrations.AlterField(
            model_name="tailleproduit",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produitTaille",
                to="produit.produit",
            ),
        ),
    ]
