# Generated by Django 4.1.4 on 2023-11-08 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produit", "0004_remove_produit_lien_image_produit_categorie_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Couleur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("code_couleur", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Pointures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taille", models.CharField(max_length=150)),
                ("disponibilite", models.CharField(max_length=150)),
                ("prix_personnalise", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="produit",
            name="couleurs",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="tailles",
        ),
        migrations.DeleteModel(
            name="tailleProduit",
        ),
        migrations.AddField(
            model_name="pointures",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produitPointure",
                to="produit.produit",
            ),
        ),
        migrations.AddField(
            model_name="couleur",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produitCouleur",
                to="produit.produit",
            ),
        ),
    ]
